import process from "process";

import builtins from "builtin-modules";
import esbuild from "esbuild";
import { copy } from "esbuild-plugin-copy";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
/** @type {import('esbuild').BuildOptions} */
const BASE_CONFIG = {
  banner: {
    js: banner,
  },
  entryPoints: ["./src/main.ts", "./src/styles.scss"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  treeShaking: true,
};

/** @type {import('esbuild').BuildOptions} */
const PROD_CONDIG = {
  watch: false,
  sourcemap: false,
  outdir: "dist",
  plugins: [
    sassPlugin(),
    copy({
      resolveFrom: "cwd",
      assets: {
        from: ["./assets/*"],
        to: ["./dist"],
      },
    }),
  ],
};

/** @type {import('esbuild').BuildOptions} */
const DEV_CONDIG = {
  watch: true,
  sourcemap: "inline",
  outdir: ".",
  plugins: [
    sassPlugin(),
    copy({
      resolveFrom: "cwd",
      assets: {
        from: ["./assets/*"],
        to: ["./"],
      },
    }),
  ],
};

const prod = process.argv[2] === "production";

esbuild
  .build({
    ...BASE_CONFIG,
    ...(prod ? PROD_CONDIG : DEV_CONDIG),
  })
  .catch(() => process.exit(1));
